export const ROOT_CONTEXT_PATH = 'http://localhost:8081/api'

export const RESET_DATA = 'RESET_DATA';

export const HIDE_NAV_BAR = 'HIDE_NAV_BAR';
export const SHOW_NAV_BAR = 'SHOW_NAV_BAR';

export const DEFAULT_UUID_ID = "00000000-0000-0000-0000-000000000000";

export const REQUEST_LOG_OUT = 'REQUEST_LOG_OUT';

export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

export const REQUEST_USERS_PENDING = 'REQUEST_USERS_PENDING';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED';

export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const REQUEST_ROLES_PENDING = 'REQUEST_ROLES_PENDING';
export const REQUEST_ROLES_SUCCESS = 'REQUEST_ROLES_SUCCESS';
export const REQUEST_ROLES_FAILED = 'REQUEST_ROLES_FAILED';